use enigo::Key as Enigo;
use wincode::{SchemaRead, SchemaWrite};
use winit::keyboard::KeyCode as Winit;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, SchemaRead, SchemaWrite)]
pub enum Key {
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Add,
    Alt,
    Backspace,
    CapsLock,
    Control,
    Decimal,
    Delete,
    Divide,
    DownArrow,
    End,
    Escape,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    Help,
    Home,
    LControl,
    LeftArrow,
    LShift,
    MediaNextTrack,
    MediaPlayPause,
    MediaPrevTrack,
    Meta,
    Multiply,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    PageDown,
    PageUp,
    #[cfg(all(unix, not(target_os = "macos")))]
    Redo,
    Return,
    RightArrow,
    Shift,
    Space,
    Subtract,
    Tab,
    UpArrow,
    VolumeDown,
    VolumeMute,
    VolumeUp,
}

impl TryFrom<Winit> for Key {
    type Error = ();

    fn try_from(key: Winit) -> Result<Self, Self::Error> {
        Ok(match key {
            Winit::NumpadAdd => Key::Add,
            Winit::AltLeft | Winit::AltRight => Key::Alt,
            Winit::Backspace => Key::Backspace,
            Winit::CapsLock => Key::CapsLock,
            Winit::SuperLeft | Winit::SuperRight | Winit::Meta => Key::Meta,
            Winit::ControlLeft | Winit::ControlRight => Key::Control,
            Winit::NumpadDecimal => Key::Decimal,
            Winit::Delete => Key::Delete,
            Winit::NumpadDivide => Key::Divide,
            Winit::ArrowDown => Key::DownArrow,
            Winit::End => Key::End,
            Winit::Escape => Key::Escape,
            Winit::F1 => Key::F1,
            Winit::F2 => Key::F2,
            Winit::F3 => Key::F3,
            Winit::F4 => Key::F4,
            Winit::F5 => Key::F5,
            Winit::F6 => Key::F6,
            Winit::F7 => Key::F7,
            Winit::F8 => Key::F8,
            Winit::F9 => Key::F9,
            Winit::F10 => Key::F10,
            Winit::Help => Key::Help,
            Winit::Home => Key::Home,
            Winit::ArrowLeft => Key::LeftArrow,
            Winit::MediaTrackNext => Key::MediaNextTrack,
            Winit::MediaPlayPause => Key::MediaPlayPause,
            Winit::MediaTrackPrevious => Key::MediaPrevTrack,
            Winit::NumpadMultiply => Key::Multiply,
            Winit::Numpad0 => Key::Numpad0,
            Winit::Numpad1 => Key::Numpad1,
            Winit::Numpad2 => Key::Numpad2,
            Winit::Numpad3 => Key::Numpad3,
            Winit::Numpad4 => Key::Numpad4,
            Winit::Numpad5 => Key::Numpad5,
            Winit::Numpad6 => Key::Numpad6,
            Winit::Numpad7 => Key::Numpad7,
            Winit::Numpad8 => Key::Numpad8,
            Winit::Numpad9 => Key::Numpad9,
            Winit::PageDown => Key::PageDown,
            Winit::PageUp => Key::PageUp,
            Winit::Enter => Key::Return,
            Winit::ArrowRight => Key::RightArrow,
            Winit::ShiftLeft | Winit::ShiftRight => Key::Shift,
            Winit::Space => Key::Space,
            Winit::NumpadSubtract => Key::Subtract,
            Winit::Tab => Key::Tab,
            Winit::ArrowUp => Key::UpArrow,
            Winit::AudioVolumeDown => Key::VolumeDown,
            Winit::AudioVolumeMute => Key::VolumeMute,
            Winit::AudioVolumeUp => Key::VolumeUp,
            _ => return Err(()),
        })
    }
}

impl From<Key> for Enigo {
    fn from(generic: Key) -> Enigo {
        match generic {
            Key::Num0 => Enigo::Unicode('0'),
            Key::Num1 => Enigo::Unicode('1'),
            Key::Num2 => Enigo::Unicode('2'),
            Key::Num3 => Enigo::Unicode('3'),
            Key::Num4 => Enigo::Unicode('4'),
            Key::Num5 => Enigo::Unicode('5'),
            Key::Num6 => Enigo::Unicode('6'),
            Key::Num7 => Enigo::Unicode('7'),
            Key::Num8 => Enigo::Unicode('8'),
            Key::Num9 => Enigo::Unicode('9'),
            Key::A => Enigo::Unicode('a'),
            Key::B => Enigo::Unicode('b'),
            Key::C => Enigo::Unicode('c'),
            Key::D => Enigo::Unicode('d'),
            Key::E => Enigo::Unicode('e'),
            Key::F => Enigo::Unicode('f'),
            Key::G => Enigo::Unicode('g'),
            Key::H => Enigo::Unicode('h'),
            Key::I => Enigo::Unicode('i'),
            Key::J => Enigo::Unicode('j'),
            Key::K => Enigo::Unicode('k'),
            Key::L => Enigo::Unicode('l'),
            Key::M => Enigo::Unicode('m'),
            Key::N => Enigo::Unicode('n'),
            Key::O => Enigo::Unicode('o'),
            Key::P => Enigo::Unicode('p'),
            Key::Q => Enigo::Unicode('q'),
            Key::R => Enigo::Unicode('r'),
            Key::S => Enigo::Unicode('s'),
            Key::T => Enigo::Unicode('t'),
            Key::U => Enigo::Unicode('u'),
            Key::V => Enigo::Unicode('v'),
            Key::W => Enigo::Unicode('w'),
            Key::X => Enigo::Unicode('x'),
            Key::Y => Enigo::Unicode('y'),
            Key::Z => Enigo::Unicode('z'),
            Key::Add => Enigo::Add,
            Key::Alt => Enigo::Alt,
            Key::Backspace => Enigo::Backspace,
            Key::CapsLock => Enigo::CapsLock,
            Key::Control => Enigo::Control,
            Key::Decimal => Enigo::Decimal,
            Key::Delete => Enigo::Delete,
            Key::Divide => Enigo::Divide,
            Key::DownArrow => Enigo::DownArrow,
            Key::End => Enigo::End,
            Key::Escape => Enigo::Escape,
            Key::F1 => Enigo::F1,
            Key::F2 => Enigo::F2,
            Key::F3 => Enigo::F3,
            Key::F4 => Enigo::F4,
            Key::F5 => Enigo::F5,
            Key::F6 => Enigo::F6,
            Key::F7 => Enigo::F7,
            Key::F8 => Enigo::F8,
            Key::F9 => Enigo::F9,
            Key::F10 => Enigo::F10,
            Key::F11 => Enigo::F11,
            Key::F12 => Enigo::F12,
            Key::F13 => Enigo::F13,
            Key::F14 => Enigo::F14,
            Key::F15 => Enigo::F15,
            Key::F16 => Enigo::F16,
            Key::F17 => Enigo::F17,
            Key::F18 => Enigo::F18,
            Key::F19 => Enigo::F19,
            Key::F20 => Enigo::F20,
            Key::Help => Enigo::Help,
            Key::Home => Enigo::Home,
            Key::LControl => Enigo::LControl,
            Key::LeftArrow => Enigo::LeftArrow,
            Key::LShift => Enigo::LShift,
            Key::MediaNextTrack => Enigo::MediaNextTrack,
            Key::MediaPlayPause => Enigo::MediaPlayPause,
            Key::MediaPrevTrack => Enigo::MediaPrevTrack,
            Key::Meta => Enigo::Meta,
            Key::Multiply => Enigo::Multiply,
            Key::Numpad0 => Enigo::Numpad0,
            Key::Numpad1 => Enigo::Numpad1,
            Key::Numpad2 => Enigo::Numpad2,
            Key::Numpad3 => Enigo::Numpad3,
            Key::Numpad4 => Enigo::Numpad4,
            Key::Numpad5 => Enigo::Numpad5,
            Key::Numpad6 => Enigo::Numpad6,
            Key::Numpad7 => Enigo::Numpad7,
            Key::Numpad8 => Enigo::Numpad8,
            Key::Numpad9 => Enigo::Numpad9,
            Key::PageDown => Enigo::PageDown,
            Key::PageUp => Enigo::PageUp,
            Key::Redo => Enigo::Redo,
            Key::Return => Enigo::Return,
            Key::RightArrow => Enigo::RightArrow,
            Key::Shift => Enigo::Shift,
            Key::Space => Enigo::Space,
            Key::Subtract => Enigo::Subtract,
            Key::Tab => Enigo::Tab,
            Key::UpArrow => Enigo::UpArrow,
            Key::VolumeDown => Enigo::VolumeDown,
            Key::VolumeMute => Enigo::VolumeMute,
            Key::VolumeUp => Enigo::VolumeUp,
        }
    }
}
