import { Menu } from "./menu.slint";
import { Button } from "std-widgets.slint";
import { FormLayout, FormSubmitButton } from "form.slint";

export component App inherits Window {
    preferred-width: 800px;
    preferred-height: 600px;

    // Enables specific components in a mutually exclusive manner
    // Options: "menu" | "share-screen-menu" | "caster" | "viewer"
    //
    // NOTE: currently this is public so that Rust code can set view to "viewer",
    // but should that be handled through callbacks instead?
    in-out property <string> view: "menu";

    // main menu
    callback start-server() -> string;
    callback start-client(server-ip: string) -> string;
    pure callback is-socket-address(address: string) -> bool;

    // input
    callback keyboard-input(key: string, action: string);
    callback escape();

    // caster/viewer menu
    in property <bool> connected: false;
    callback select-role(role: string) -> string;

    // viewer
    in property <image> video-frame <=> viewer.source;

    if view == "menu": Menu {
        start-server() => {
            let error = root.start-server();
            if (error == "") {
                root.view = "share-screen-menu";
            }
            error
        }
        start-client(server-ip) => {
            let error = root.start-client(server-ip);
            if (error == "") {
                root.view = "share-screen-menu";
            }
            error
        }
        is-socket-address(address) => root.is-socket-address(address);
    }

    forward-focus: scope;

    scope := FocusScope {
        width: 100%;
        height: 100%;

        KeyBinding {
            keys: @keys(Escape);
            activated => {
                escape();
                if (root.view == "menu") {
                    root.close();
                } else {
                    root.view = "menu";
                }
            }
        }

        key-pressed(event) => {
            if (view == "viewer" && !event.modifiers.meta && !event.modifiers.alt) {
                root.keyboard-input(event.text, "pressed");
            }
            accept
        }
        key-released(event) => {
            if (view == "viewer" && !event.modifiers.meta && !event.modifiers.alt) {
                root.keyboard-input(event.text, "released");
            }
            accept
        }
    }

    if (!connected && view != "menu"): VerticalLayout {
        VerticalLayout {
            Text {
                text: "Waiting for connection...";
            }
        }
    }

    if (view == "share-screen-menu" && connected): HorizontalLayout {
        alignment: center;
        
        FormLayout {
            FormSubmitButton {
                text: "Share Screen";
                validate() => true;
                submit() => {
                    let error = select-role("caster");
                    if (error == "") {
                        root.view = "caster";
                    }
                    error
                }
            }
        }

        Rectangle {
            width: 7%;
        }

        FormLayout {
            FormSubmitButton {
                text: "Watch";
                validate => true;
                submit => {
                    let error = select-role("viewer");
                    if (error == "") {
                        root.view = "viewer";
                    }
                    error
                };
            }
        }
    }

    if (view == "caster" && connected): VerticalLayout {
        VerticalLayout {
            Text {
                text: "Sharing screen";
            }
        }
    }

    VerticalLayout {
        visible: view == "viewer" && connected;

        viewer := Image { }
    }
}
