import { MainMenu, RoleSelectMenu } from "./menu.slint";
import { Button } from "std-widgets.slint";
import { FormLayout, FormSubmitButton } from "form.slint";

export component App inherits Window {
    preferred-width: 800px;
    preferred-height: 600px;

    // Enables specific components in a mutually exclusive manner
    // Options: "main-menu" | "role-select-menu" | "streamer" | "watcher"
    private property <string> view: "main-menu";

    // main menu
    callback start-server() -> string;
    callback start-client(server-ip: string) -> string;
    pure callback is-socket-address(address: string) -> bool;

    // input
    callback keyboard-input(key: string, action: string);
    callback escape();

    // streamer/watcher menu
    in property <bool> connected: false;
    callback select-role(role: string) -> string;

    // watcher
    in property <image> video-frame <=> watcher.source;

    if view == "main-menu": MainMenu {
        start-server() => {
            let error = root.start-server();
            if (error == "") {
                root.view = "role-select-menu";
            }
            error
        }
        start-client(server-ip) => {
            let error = root.start-client(server-ip);
            if (error == "") {
                root.view = "role-select-menu";
            }
            error
        }
        is-socket-address(address) => root.is-socket-address(address);
    }

    forward-focus: scope;

    scope := FocusScope {
        width: 100%;
        height: 100%;

        KeyBinding {
            keys: @keys(Escape);
            activated => {
                escape();
                if (root.view == "main-menu") {
                    root.close();
                } else {
                    root.view = "main-menu";
                }
            }
        }

        key-pressed(event) => {
            if (view == "watcher" && !event.modifiers.meta && !event.modifiers.alt) {
                root.keyboard-input(event.text.to-lowercase(), "pressed");
            }
            accept
        }
        key-released(event) => {
            if (view == "watcher" && !event.modifiers.meta && !event.modifiers.alt) {
                root.keyboard-input(event.text.to-lowercase(), "released");
            }
            accept
        }
    }

    if (!connected && view != "main-menu"): VerticalLayout {
        alignment: center;
        
        VerticalLayout {
            Text {
                horizontal-alignment: center;
                vertical-alignment: center;
                text: "Waiting for connection...";
            }
        }
    }

    if (view == "role-select-menu" && connected): RoleSelectMenu {
        select-role(role) => {
            let error = root.select-role(role);
            if (error == "") {
                root.view = role;
            }
            error
        }
    }

    if (view == "streamer" && connected): VerticalLayout {
        VerticalLayout {
            Text {
                text: "Sharing screen";
            }
        }
    }

    VerticalLayout {
        visible: view == "watcher" && connected;

        watcher := Image { }
    }
}
