import { FormSubmitButton, FormLayout, FormField } from "./form.slint";
import { Role } from "./role.slint";

export component MainMenu inherits HorizontalLayout {
    alignment: center;

    callback start-server(role: Role) -> string;
    callback start-client(server-ip: string) -> string;
    pure callback is-socket-address(text: string) -> bool;

    HorizontalLayout {
        FormLayout {
            FormSubmitButton {
                text: "Host as Streamer";
                validate => true;
                submit => start-server(Role.streamer);
            }
        }

        Rectangle {
            width: 7%;
        }

        FormLayout {
            FormSubmitButton {
                text: "Host as Watcher";
                validate => true;
                submit => start-server(Role.watcher);
            }
        }
    }

    Rectangle {
        width: 7%;
    }

    FormLayout {
        server-ip-field := FormField {
            height: 7%;
            placeholder-text: "Enter server address (e.g. 192.168.1.1)";
            validate(text) => is-socket-address(text) ? "" : "Invalid address";
        }

        FormSubmitButton {
            text: "Connect";
            validate() => server-ip-field.is-valid();
            submit() => start-client(server-ip-field.text);
        }
    }
}
